### ISSUE TITLE
Custom fields in log statement?

### ISSUE THREAD

**Issue by maros7** [gin-contrib/zap#13]
Hi, I'm wondering if you'd consider a PR for adding functionality to make it possible to add custom fields to the log statement? E.g. by having something like:

```go
func WithCustomFields(logger *zap.Logger,
	timeFormat string,
	utc bool,
	customFields ...func(c *gin.Context) zap.Field,
) gin.HandlerFunc {

...
```

Our use-case is that we need to log the return headers.

**Comment by maros7** [comment]
👍

**Comment by thinkgos** [comment]
@maros7 this package https://github.com/things-go/gzap may meet you need.

**Comment by appleboy** [comment]
See https://github.com/gin-contrib/zap#custom-zap-fields
