### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by LeKovr** [gin-contrib/zap#15]
As this repo has no any version, so any log line contains `"caller":"zap@v0.0.0-20191128031730-d12829f8f61b/zap.go:46"`

Would you like please to make a tag so this string will be shorter or remove caller even

**Comment by appleboy** [comment]
@LeKovr Added the tag v0.0.1

**Comment by LeKovr** [comment]
> @LeKovr Added the tag v0.0.1

@appleboy, thanks
