### ISSUE TITLE
GinzapWithConfig is not available in v0.0.1

### ISSUE THREAD

**Issue by abhic91** [gin-contrib/zap#20]
I don't see the `GinzapWithConfig` in `zap.go` when I `go get github.com/gin-contrib/zap`

I am trying to use the `skipPaths` options but the `GinzapWithConfig` isn't there

```
r.Use(ginzap.GinzapWithConfig(utcLogger, &Config{
    TimeFormat: time.RFC3339,
    UTC: true,
    SkipPaths: []string{"/no_log"},
}))
```

**Comment by mwilliams-rcd** [comment]
Until a new release/tag is published you can use a commit like `go get github.com/gin-contrib/zap@de3bf1063d79` instead of letting go mod decide on the version.

**Comment by rwong2888** [comment]
When will a new release be published?

**Comment by appleboy** [comment]
See the version v0.0.2 https://github.com/gin-contrib/zap/releases/tag/v0.0.2
