### ISSUE TITLE
request body Custom Zap fields can't get body

### ISSUE THREAD

**Issue by wentaojin** [gin-contrib/zap#65]
PUT request，zap log output "body": ""，but request body is json

	r.Use(ginzap.GinzapWithConfig(logger.GetRootLogger().With(zap.String("component", "gin")), &ginzap.Config{
		TimeFormat: logger.LogTimeFmt,
		UTC:        false,
		Context: func(c *gin.Context) []zapcore.Field {
			var fields []zapcore.Field

			// log request body
			var body []byte
			var buf bytes.Buffer
			tee := io.TeeReader(c.Request.Body, &buf)
			body, _ = io.ReadAll(tee)
			c.Request.Body = io.NopCloser(&buf)

			fields = append(fields, zap.String("body", string(body)))

			return fields
		}}))

**Comment by SavostinVladimir** [comment]
You see this because this lib invokes c.Next() under the hood before invoke Context Fn. So in the handler you have already read the body and req.Body now is empty. To solve, you can fork this lib and place invocation of Context Fn before c,Next()
